# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Saleh Parsa

description: Stylish Jekyll Theme
author:
  name: Saleh Parsa
  email: salehp@gmail.com
  github: salehparsa
  twitter: salehp
  pinterest: asd123
  linkedin: saleh-parsa-49554072
  bio: Your stylish, minimalist theme!
  email_md5: 718f0a1709df67b1492f7e7cba5422c6

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate